basic.show_icon(IconNames.HEART)
def on_forever():
    pass
basic.forever(on_forever)
#hhajklfůdljkůdsfjkůldskljů sdfjklů jkůlds fůjk ad fjkkdlsj flkůs dajfkljsadklf jklsad jflasjkdfjdslkjůdfsajklůfsdaljkfdsjklljkůdfsjkldfsljksdfa kldfsjklsdafjklůfjsdklaůjfklůasdjflksadjflůkjldfsjkldfkljůdfsjklůdfsljksdfljkjkldfskljdfskljůdfsjkldfsajfklůasjd ioufjdsifjiouwjnakljfjsdkjfsadjfkljůsadfiůojdklfjjkljewhiůofjskldjflksajfdoidsfsdkjfůiosadjfkldsjůlkfujdskljfklůdsjfsadjfkljsadklfjjsadlkůfjdklsůjfklsadjfkůldsjfrůlksadjkflůkljůdsjdfia
led.plot(0, 0)